### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Monma9955** [Monma9955/chat-space#15]
# IPアドレス
18.177.15.237

**Comment by kohei-isoda** [comment]
門馬さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◯ ユーザー編集をしようとすると以下のエラーが出る**
[![Screenshot from Gyazo](https://gyazo.com/3f54d9dc7133031d57f2cbe143c50959/raw)](https://gyazo.com/3f54d9dc7133031d57f2cbe143c50959)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by kohei-isoda** [comment]
再提出ありがとうございます！
確認させて頂いたところ、修正点が無くなっておりましたのでLGTMとさせて頂きます🎉
修正お疲れ様でした、おめでとうございます！

**Comment by Monma9955** [comment]
申し訳ございません、通知が有効になっていなくてすぐに気付けませんでした。
確認ありがとうございました！
